services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DB_HOST: "database"
      DB_USER: "user"
      DB_PASSWORD: "userpassword"
      DB_NAME: "simpledb"
    restart: on-failure

  database:
    build: ./database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure

volumes:
  db_data: