services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DB_HOST: "squad-track-database.cmwrzzcezjll.us-east-1.rds.amazonaws.com"
      DB_USER: "admin"
      DB_PASSWORD: "adminadmin"
      DB_NAME: "simpledb"
    restart: on-failure
    networks:
      - my-network

  database:
    build: ./database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
    driver: bridge